// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FeedAPI.Models
{
    public partial class FeedInformation
    {
        public int Id { get; set; }
        public DateTime? CreationTime { get; set; }
        public string Manufacturer { get; set; }
        public string ItemNumber { get; set; }
        public string ItemName { get; set; }
        public string Material { get; set; }
        public decimal? Wire { get; set; }
        public decimal? Length { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? Cost { get; set; }
        public decimal? Raise { get; set; }
        public string Class { get; set; }
        public string Description { get; set; }
        public bool? IsDeleted { get; set; }
    }
}